### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hirani89** [appzer/pushsafer-arduino-library#3]
Hi,

I really appreciate you made this library but it does not seem to work.

Is it because of the new changes you made a couple of weeks ago?

When I try with Postman, it works.

WiFi connection is successful as well.

My test code below:

```
#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>
#include <Pushsafer.h>

// Initialize Wifi connection to the router

// Pushsafer private or alias key
#define PushsaferKey "mykey"

WiFiClientSecure client;
Pushsafer pushsafer(PushsaferKey, client);

void setup() {
  Serial.begin(115200);

  // Set WiFi to station mode and disconnect from an AP if it was Previously
  // connected
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  delay(100);

  // Attempt to connect to Wifi network:
  Serial.print("Connecting Wifi: ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  pushsafer.debug = true;
  
  struct PushSaferInput input;
  input.message = "This is a test message";
  input.device = "a";


  Serial.println(pushsafer.sendEvent(input));
  Serial.println("Sent");
}

void loop() {
}
```

**Comment by appzer** [comment]
can you provide an error log

**Comment by hirani89** [comment]
How do I get the logs?

**Comment by appzer** [comment]
[https://arduino.stackexchange.com/questions/11601/how-to-see-log-from-arduino-ide](https://arduino.stackexchange.com/questions/11601/how-to-see-log-from-arduino-ide)

**Comment by hirani89** [comment]
All I get in the Serial Monitor is the following:

```
WiFi connected
IP address: 172.16.101.14

Sent
```

**Comment by hirani89** [comment]
After changing the library code to output more information about the whole process, I realised that the code fails on `if (client->connect(HOST, SSL_PORT)) `.

I have made sure the this works with postman or curl from terminal.

**Comment by appzer** [comment]
you need SSL support, because the api communicate over https

**Comment by hirani89** [comment]
So how do I fix this?

**Comment by appzer** [comment]
here you will find the necessary informations:
[https://arduino.stackexchange.com/questions/4/how-to-get-https-on-arduino](https://arduino.stackexchange.com/questions/4/how-to-get-https-on-arduino)
