### ISSUE TITLE
doesnt fit with Arduino WiFi R2

### ISSUE THREAD

**Issue by Yujie-Zhao** [appzer/pushsafer-arduino-library#5]
It doesnt work with an Arduino WiFi R2. The error message shows that: "Error compiling for board Arduino Uno WiFi Rev2."
Is there any easy way to adjust the code to fit that?

Thank you very much!

**Comment by appzer** [comment]
do you have an detailed error log

**Comment by Yujie-Zhao** [comment]
Arduino: 1.8.14 Hourly Build 2020/09/23 10:33 (Windows 10), Board: "Arduino Uno WiFi Rev2, None (ATMEGA4809)"

Multiple libraries were found for "Pushsafer.h"

 Used: C:\Users\yz90\Documents\Arduino\libraries\Pushsafer

 Not used: C:\Users\yz90\Documents\Arduino\libraries\appzer-pushsafer-arduino-library-7389867

In file included from C:\Users\yz90\Documents\Programming\Arduino\Pushsafer_sensor\Pushsafer_sensor.ino:2:0:

C:\Users\yz90\Documents\Arduino\libraries\Pushsafer\src/Pushsafer.h:27:10: fatal error: ArduinoJson.h: No such file or directory

 #include <ArduinoJson.h>

          ^~~~~~~~~~~~~~~

compilation terminated.

exit status 1

Error compiling for board Arduino Uno WiFi Rev2.



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.




It looks like I had several copies of this library so it shows some error. I am not sure about the 'ArduinoJson.h' error. Thank you for your time.

**Comment by Yujie-Zhao** [comment]
Also, because Arduino WiFi R2 supports WiFi by itself, no external shield is required. We can directly use 'WiFiNINA.h' to connect with network. I have modified the example code to fit this, but there is some issue with the pushsafer library.

**Comment by appzer** [comment]
Please use a arduino board to get help. I'am not a pro in this!

**Comment by Yujie-Zhao** [comment]
Thanks anyway! I will have a look on it.

Best regards,
