### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by svdrummer** [appzer/pushsafer-arduino-library#6]
Latest compile error. Have I missed something?
C:\Users\cruis\Documents\Arduino\libraries\pushsafer-arduino-library-master\src\Pushsafer.cpp: In member function 'String Pushsafer::sendEvent(PushSaferInput)':
C:\Users\cruis\Documents\Arduino\libraries\pushsafer-arduino-library-master\src\Pushsafer.cpp:75:14: error: 'struct PushSaferInput' has no member named 'time2live'
     if(input.time2live != "")
              ^
C:\Users\cruis\Documents\Arduino\libraries\pushsafer-arduino-library-master\src\Pushsafer.cpp:77:72: error: 'struct PushSaferInput' has no member named 'time2live'
       start_request = start_request + buildString(boundary, "l", input.time2live);
                                                                        ^
C:\Users\cruis\Documents\Arduino\libraries\pushsafer-arduino-library-master\src\Pushsafer.cpp:113:10: warning: unused variable 'c' [-Wunused-variable]
     char c;
          ^

**Comment by appzer** [comment]
All works fine!
Simple copy all downoaded files to your Arduino Libraries folder

`Arduino\libraries\pushsafer-arduino-library
`

![Zwischenablage01](https://user-images.githubusercontent.com/3443312/108604466-6e7b2500-73ae-11eb-8a1d-f187d3f5d891.jpg)

**Comment by svdrummer** [comment]
As can be seen. I have the files in the library folder. I used library
manager to get them there.
The time2 section is throwing an issue.
I will delete all and try a manual copy paste.
