### ISSUE TITLE
Reopen as last issue was not dealt with. and prematurely closed.

### ISSUE THREAD

**Issue by svdrummer** [appzer/pushsafer-arduino-library#7]
Arduino version 1.8.13
Experience level (Advanced user)

Library is loaded and re-loaded where it should be. Arduino\libraries\pushsafer-arduino-library

#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>
//#include <WiFiClient.h>// THis was added to match the sample file used to compile in the 
#include <Pushsafer.h>

My header includes are from the example which the test program used to say there isn't a fault, has different include.

I am using one of our official production Wemos D1-mini devices.

"C:\\Users\\cruis\\AppData\\Local\\Arduino15\\packages\\esp8266\\tools\\xtensa-lx106-elf-gcc\\2.5.0-4-b40a506/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-IC:\\Users\\cruis\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.7.4/tools/sdk/include" "-IC:\\Users\\cruis\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.7.4/tools/sdk/lwip2/include" "-IC:\\Users\\cruis\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.7.4/tools/sdk/libc/xtensa-lx106-elf/include" "-IC:\\Users\\cruis\\AppData\\Local\\Temp\\arduino_build_897810/core" -c -Wall -Wextra -Os -g -mlongcalls -mtext-section-literals -fno-rtti -falign-functions=4 -std=gnu++11 -MMD -ffunction-sections -fdata-sections -fno-exceptions -DNONOSDK22x_190703=1 -DF_CPU=80000000L -DLWIP_OPEN_SRC -DTCP_MSS=536 -DLWIP_FEATURES=1 -DLWIP_IPV6=0 -DARDUINO=10813 -DARDUINO_ESP8266_WEMOS_D1MINI -DARDUINO_ARCH_ESP8266 "-DARDUINO_BOARD=\"ESP8266_WEMOS_D1MINI\"" -DFLASHMODE_DIO -DESP8266 "-IC:\\Users\\cruis\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.7.4\\cores\\esp8266" "-IC:\\Users\\cruis\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.7.4\\variants\\d1_mini" "-IC:\\Users\\cruis\\AppData\\Local\\Arduino15\\packages\\esp8266\\hardware\\esp8266\\2.7.4\\libraries\\ESP8266WiFi\\src" "-IC:\\Users\\cruis\\Documents\\Arduino\\libraries\\pushsafer-arduino-library\\src" "-IC:\\Users\\cruis\\Documents\\Arduino\\libraries\\ArduinoJson\\src" "C:\\Users\\cruis\\Documents\\Arduino\\libraries\\pushsafer-arduino-library\\src\\Pushsafer.cpp" -o "C:\\Users\\cruis\\AppData\\Local\\Temp\\arduino_build_897810\\libraries\\pushsafer-arduino-library\\Pushsafer.cpp.o"
C:\Users\cruis\Documents\Arduino\libraries\pushsafer-arduino-library\src\Pushsafer.cpp: In member function 'String Pushsafer::sendEvent(PushSaferInput)':
C:\Users\cruis\Documents\Arduino\libraries\pushsafer-arduino-library\src\Pushsafer.cpp:75:14: error: 'struct PushSaferInput' has no member named 'time2live'
     if(input.time2live != "")
              ^
C:\Users\cruis\Documents\Arduino\libraries\pushsafer-arduino-library\src\Pushsafer.cpp:77:72: error: 'struct PushSaferInput' has no member named 'time2live'
       start_request = start_request + buildString(boundary, "l", input.time2live);
                                                                        ^
C:\Users\cruis\Documents\Arduino\libraries\pushsafer-arduino-library\src\Pushsafer.cpp:113:10: warning: unused variable 'c' [-Wunused-variable]
     char c;
          ^
Multiple libraries were found for "ArduinoJson.h"
 Used: C:\Users\cruis\Documents\Arduino\libraries\ArduinoJson
 Not used: C:\Users\cruis\Documents\Arduino\libraries\arduino_863954
 Not used: C:\Users\cruis\Documents\Arduino\libraries\ArduinoJson-old
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\cruis\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi 
Using library pushsafer-arduino-library at version 1.0.0 in folder: C:\Users\cruis\Documents\Arduino\libraries\pushsafer-arduino-library 
Using library ArduinoJson at version 6.17.3 in folder: C:\Users\cruis\Documents\Arduino\libraries\ArduinoJson 

exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

If I remove time2live from the Pushsafer.h file...the file compiles okay, but then  the sketch doesn't work with my paid pushsaver account.

I also noted that the samples run last time to show this will compile, was not the standard example file. For example, This was commented out "#include <WiFiClientSecure.h>" and wifiClient.h was used.

Lets compare apples for apples here and look at this issue subjectively please.

**Comment by svdrummer** [comment]
THis is the example sketch as supplied with the library for an ESP8266


#include <ESP8266WiFi.h>
#include <WiFiClientSecure.h>
#include <Pushsafer.h>

// Initialize Wifi connection to the router
char ssid[] = "ssid";     // your network SSID (name)
char password[] = "password"; // your network key

// Pushsafer private or alias key
#define PushsaferKey "XXXXXXXXXXXXX"

WiFiClientSecure client;
Pushsafer pushsafer(PushsaferKey, client);

void setup() {
  Serial.begin(115200);

  // Set WiFi to station mode and disconnect from an AP if it was Previously
  // connected
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  delay(100);

  // Attempt to connect to Wifi network:
  Serial.print("Connecting Wifi: ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);

  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());

  pushsafer.debug = true;

  struct PushSaferInput input;
  input.message = "This is a test message";
  input.title = "Hello!";
  input.sound = "8";
  input.vibration = "1";
  input.icon = "1";
  input.device = "a";

  // API description: https://www.pushsafer.com/en/pushapi
  // Other optional Options
  // input.url;
  // input.urlTitle;
  // input.picture;
  // input.picture2;
  // input.picture3;
  // input.time2live;

  Serial.println(pushsafer.sendEvent(input));
  Serial.println("Sent");
}

void loop() {
}

**Comment by appzer** [comment]
for me all works fine! I'am not a pro for arduino. So please search help from Arduino users in a forum like this: https://forum.arduino.cc/

**Comment by svdrummer** [comment]
Seems what you have is different from the example in the library. Sorry, I thought you wrote this library. It seems to have been written by another person and copied to here.

**Comment by svdrummer** [comment]
I have just reloaded the library. Seems different than a few days ago.
The CPP code has changed. Now it works okay.
Cheers
To help others. Make sure your library example starts with
#include <ESP8266WiFi.h>
/*#include <WiFiClientSecure.h>*/
#include <WiFiClient.h>
#include <Pushsafer.h>
If anything different, it will not compile
Matter closed
